services:
  api:
    image: yasathedogxx/nine-lancache-ui:api
    restart: unless-stopped
    network_mode: "host"
    environment:
      - LanCacheLogsDirectory=/var/ninelancacheui/lancachelogs
      - LanCacheUIDataDirectory=/var/ninelancacheuidata
      - ConnectionStrings__DefaultConnection=Data Source={LanCacheUIDataDirectory}/database/nine-lancache-ui.db;
      - TZ=Europe/Amsterdam
      - ASPNETCORE_ENVIRONMENT=Production
      - LANG=en_US.UTF-8
      - DirectSteamIntegration=true
      - SkipLinesBasedOnBytesRead=true
      - ASPNETCORE_HTTP_PORTS=7401
    volumes:
      - "/volume1/docker/SteamGames/backendData:/var/ninelancacheuidata"
      - "/volume1/docker/SteamGames/logs:/var/ninelancacheui/lancachelogs:ro"
    dns:
      - 192.168.1.115
  ui:
    image: yasathedogxx/nine-lancache-ui:ui
    restart: unless-stopped
    network_mode: "host"
    environment:
      - API_BASE_URL=http://192.168.1.115:7401
      - AllowedHosts=*
