// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NineLanCacheUI_API.Data;

#nullable disable

namespace NineLanCacheUI_API.Migrations
{
    [DbContext(typeof(NineLanCacheUIDBContext))]
    [Migration("20250723192518_AddExcludedIps")]
    partial class AddExcludedIps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NineLanCacheUI_API.Data.Tables.DbDownloadEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CacheHitBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CacheIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CacheMissBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DownloadIdentifier")
                        .HasColumnType("bigint");

                    b.Property<string>("DownloadIdentifierString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CacheIdentifier");

                    b.HasIndex("ClientIp");

                    b.ToTable("DownloadEvents");
                });

            modelBuilder.Entity("NineLanCacheUI_API.Data.Tables.DbExcludedIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("ExcludedIps");
                });

            modelBuilder.Entity("NineLanCacheUI_API.Data.Tables.DbSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("NineLanCacheUI_API.Data.Tables.DbSteamDepot", b =>
                {
                    b.Property<long>("SteamDepotId")
                        .HasColumnType("bigint");

                    b.Property<long>("SteamAppId")
                        .HasColumnType("bigint");

                    b.HasKey("SteamDepotId", "SteamAppId");

                    b.ToTable("SteamDepots");
                });

            modelBuilder.Entity("NineLanCacheUI_API.Data.Tables.DbSteamManifest", b =>
                {
                    b.Property<long>("DepotId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ManifestBytesSize")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("TotalCompressedSize")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("TotalUncompressedSize")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("UniqueManifestIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepotId", "CreationTime");

                    b.HasIndex("UniqueManifestIdentifier")
                        .IsUnique();

                    b.ToTable("SteamManifests");
                });
#pragma warning restore 612, 618
        }
    }
}
